server:
  port: 9090
management:
  security:
    enabled: false #关掉安全认证
  port: 9099 #管理端口调整成9099
  context-path: /monitor #actuator的访问路径
endpoints:
  shutdown:
    enabled: true

info:
   app:
      name: spring-boot-actuator
      version: 1.0.0